name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      volumeId:
        description: 'Deleted EBS volume id'
        required: true
        default: 'none'
      region:
        description: 'Region name'
        required: false
        default: 'eu-west-1'
jobs:
  notify_deletion:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "The Volume ${{ github.event.inputs.volumeId }} has been deleted in the ${{ github.event.inputs.region }} region!"
